# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40508b6a327cc59d08a472a7bb28f54cba806c116b4dab317cdbb0d983cdddb8e6a361b1aba696bedb358305a2fb536fc9d3cde7d712319fc358cdf1ef19e87e

test:
  secret_key_base: d5b36fc78e8f85435847118ecbf4245488917c6b561c8a1febe7ebf14367cfe24255aaba48dbc38f81457d371bd5810d5cf89f5b5d6400c127c96ce7385a506f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
